from typing import TypedDict, Annotated, List, Literal
import operator

class AgentState(TypedDict):
    # User's raw audio transcript or text input
    user_input: str
    
    # Internal context
    session_id: str
    chat_history: List[str]
    
    # Execution
    plan: List[str]          # Steps generated by planner
    current_step: int        # Index of current tool execution
    tool_outputs: List[str]  # Raw tool data
    
    # Draft Response
    draft_response: str      # Executor's synthesized response
    
    # Critic validation
    critic_notes: str        # Critic's feedback
    is_valid: bool           # Did critic approve?
    
    # Final artifacts sent to frontend
    final_response: str      # Response to send to TTS
    ui_commands: List[dict]  # JSON commands for Flutter
    
    # Session Memory (V2)
    last_property_id: str    # ID of the last mentioned property
    user_prefs: dict         # Persistent user preferences (e.g. { "area": "West Bay" })
